### ISSUE TITLE
Collapse folders/scripts

### ISSUE THREAD

**Issue by msheldont4e** [Tools4everBV/HelloID-Conn-SA-Full-AD-DelegatedPasswordReset#2]
We need to collapse the Config app and the reset app into one "All-In-One setup" folder. This is part of the standards we are putting in place.

**Comment by rschouten97** [comment]
Agreed, this should be reworked into 2 different repositories.
Otherwise the Github Integration won't work either.

**Comment by rschouten97** [comment]
**Notice: Repository Archival**

The 'all-in-one' create scripts are currently non-functional, suggesting that this form/repository is no longer in use. In light of this, we have decided to archive this repository. Unfortunately, we are unable to easily split this into two separate repositories since we do not utilize this internally, and the existing scripts are not operational.

Should there be a continued need for this repository and its functionalities, we are open to unarchiving it. However, it will require someone who actively uses this repository to overhaul its contents.

Thank you for your understanding.
